# language
language: php

# php versions to test against
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

# install dependencies
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --no-suggest

# Notifications example
#notifications:
  #slack: slack-token-here-if-needed

# test it!
script:
  - phpunit --process-isolation --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
